repository:
  name: module-azurerm-sa
  description: Terraform module which creates storage resources on Azure.
  homepage: https://github.com/aztfmods/module-azurerm-sa
  topics: module, storage
  private: true
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: integration
    color: '#FEF2C0'
    description: integration
  - name: module
    color: '#7BE107'
    description: module
  - name: 'needs refinement'
    color: '#B533B3'
    description: 'needs refinement'
  - name: bug
    color: '#B60205'
    description: bug
